# Generated by Django 2.0.5 on 2019-02-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('scale', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('itemPrice', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cebolla.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderPrice', models.IntegerField(default=0)),
                ('ongoing', models.BooleanField(default=False)),
                ('receiving', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='rfID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='rfID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='cebolla.rfID'),
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cebolla.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('order', 'ingredient')},
        ),
    ]
